name: Huffify CI pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # specify the Python version you want to use

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
            
    - name: Install dependencies
      run: poetry install

    - name: Make
      run: make lint
