name: Huffify CI pipeline

on: [push, release]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    
    - name: Lock dependencies
      run: poetry lock

    - name: Install dependencies
      run: poetry install

    - name: Make
      run: make --keep-going format lint

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.4
    
    - name: Lock dependencies
      run: poetry lock

    - name: Install dependencies
      run: poetry install

    - name: Make
      run: make --keep-going tests
